language: php

sudo: false

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

branches:
  only:
    - master

git:
  depth: 5

cache:
  directories:
  - $HOME/.composer/cache

env:
  global:
    - secure: WM6/jFIv5y0fucZqd2kUhHindfgyz2UkRfDor/e+BEeqN9JfJD5kVDyLHIbHSvGXWYah5Nk56I6Wwo3HjPgsdKU1tfatYBNMqRzKHa13sChd4idIrpUJBRKGqWDJeh3h6Cnf5DrudUKPh7AdDN8Nz5kC+CAo5M3LpM919Qu8mz0=
    - secure: U/F0aSA/ryVple78OsCjTdnfD+633FSupEfVogdwtdvcVus1588zkDmOYnI7ZOAvbcwlfq+RmPBNObxu7kRk0YWzyfQ/eWwWEDMrTP40+HwYrb++Dxbmi8eGqSBX7XfikAZkuS6tBES+7RKGtZhlXAh77zEdDhYkZVuDzOJwO6c=
    - secure: fuPJkgdJqR88vOcKi7s7UMNCNdlHbxhfAk4vxQPh82070sZ6bV95/2IypEQHAIsoyLmP2nSDlsTn5ROwPQaDL0zqii0WMueLYHwKbOx1If4yslDjMpuQ7Qv5Wbrid4mhak0O0sWvgFd20Q5hBbnaV6uCEcorqdwabrm9/oKF4zw=
    - secure: c9r0P1Ey2jKqtAY3WIHz+lQ7x+ZW70Jtn24ZIWwRQG2jqY0l4VTC7tkE1RGBnNYyfDrdRYFnIuQ5xC8iMNp3R3NdPtbqo0Hwe3cA+lEfpuZ0XyPHTl0dywYijYmwr3vWtPLq8LnYbAOV53fYuFI/jE2WaGVw0A5F2Stsa0Im52w=
    - secure: MXb0FdlZZPAinvZ60iSpL55xrJ9Gd91u5427apa3WTz5koybB5eMn5QoFkUlOU02u0vmLSWTGo5OK1/P/5MS1kewXVLIzu+L0nIAjnbTUi9JjVQiV6Kpl3MCzr12T0zQ3JNvGUi85t612VA4S4so9Yh/LOBfhUNASPtqX3Mrhkw=
    - secure: CNqIU+dzcH6MKsiFaa+N3j9WS7kra4ajwZ0E+Z6UiLH8I62vN1eBwCj5ibRrs8cFdMtkAD+DFGntqe9OjJI7f2pc8o9ZMLls4siACju0jPECPWDlDIpOzrksqVCHdgE3epnJOIQ+Wgtw43/TKoPLYD4TwzUDS4yG/0UjgSvftWU=
    - secure: GMeb9x2HLs701pTYpM5y7omKcFxPdpsCd1Yb8vxmD73kIgGwccv3vliOL59cHuKkJfdktNUAel0K6XUHAd77cYwxsI3GHSeSvatYXsI2o6t8b2wHLMro4XqR+GlVBXY39ocKieJFrbmTSWXvQmPBENlz2oerW69NtybXV/4eLaQ=
    - secure: L/zdXZ/QvLoKzi9waLoktc/zY6IluQX2YxYTfxfVXnH3uMNvBL2ULd4FiwCHhFF8Scg1XxfS5XrdQ1jhkwBXmdNubu36bxMbCcYYtgJ8clgKt/YuN8gD46uwB2CIY+RHIFVYlnnPx4KvAAo3ZD4LpqA3p2PKIJAejXVfugEzNxg=
    - secure: YYKm9uiW+zz3tA4k3r8PAGSTZXXAUw1rByN48FfvxRIMjxwawxyes7XI+bMy0HCdycp1eJclYNxB14MyLJH4VfsR4FmcFQvHnsNV8m3l93tezie82fBT5iwZpWttkJoUnwkWIltKXh3WlsErY07jMCtsto8SfaRcHzUL0Zr+svo=
    - secure: Vl5+/D22WmpwMhzIMVLZU559Mkblw6W5PMJq/bIOORaCpX5E7deBjKzFtRn+McJNvR3lewMF5yFxnEdJBYB7SzVQ10gExGTfVCE9YwlKUzfVo/0rufPjal10vKI42nCr7aThSKpxRo7leAivzOBxTMcWakg+p4+5AfdmAGiO17c=

notifications:
  email: false
  slack:
    secure: JhetEEPz5c84CuTDHks86k6IpUAlv7LFGswafXCMO5/ztXHMU2Mv6w6jnvp/YOuqiX0nWPRJCbRfoVXdEb/VO/AcLDkscwa10foSziPfbjqofNZ/b2+MtQ93UbfHGpFNIUUrMVnY9/7YW9a6TrPqHT196/+B59L/457RWJz0tC0=

install:
  - travis_retry composer install --no-interaction --no-progress --prefer-dist

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `OpenBuildings/purchases`;'
  - mysql --default-character-set=utf8 OpenBuildings/purchases < tests/test_data/structure.sql

script:
  - vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
